services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DOCKER_DB_DATABASE:-testing}
      DB_USERNAME: ${DOCKER_DB_USERNAME:-docker}
      DB_PASSWORD: ${DOCKER_DB_PASSWORD:-password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - '${DOCKER_APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    ports:
      - '${DOCKER_DB_PORT:-3306}:3306'
    container_name: laravel_db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DOCKER_DB_DATABASE}:-testing'
      MYSQL_USER: '${DOCKER_DB_USERNAME}:-docker'
      MYSQL_PASSWORD: '${DOCKER_DB_PASSWORD}:-password'
      MYSQL_ROOT_PASSWORD: '${DOCKER_DB_PASSWORD}:-password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DOCKER_DB_PASSWORD}:-password'
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    ports:
      - '${DOCKER_REDIS_PORT:-6379}:6379'
    container_name: laravel_redis
    volumes:
      - redisdata:/data
    networks:
      - laravel
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    ports:
      - '${DOCKER_MAILHOG_SMTP_PORT:-1025}:1025'
      - '${DOCKER_MAILHOG_WEB_PORT:-8025}:8025'
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
