name: tests

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: '8.4'
      node-version:
        required: false
        type: string
        default: '22'
      coverage-threshold:
        required: false
        type: number
        default: 80

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer:v2
          extensions: mbstring, pdo, pdo_mysql, redis
          coverage: pcov

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Laravel
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate

      - name: Tests
        run: ./vendor/bin/pest --coverage --min=${{ inputs.coverage-threshold }}
